[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

# Add a specific rule for the CV file to prevent it from being redirected to index.html
[[redirects]]
  from = "/Yuang-Tong-CV.pdf"
  to = "/Yuang-Tong-CV.pdf"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Redirección  crucial para aplicaciones SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200