[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Esta redirección es crucial para aplicaciones SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200